# Base image
FROM node:10

# Move to app folder
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy the app code to the image
COPY . .
EXPOSE 8080
CMD [ "npm", "start" ]

# Node-specific files
node_modules
npm-debug.log

# Other IDE-specific folders
nbproject
.vscode
